const translations = {
    'en': {
        'welcome': 'Welcome to CheckSpeech AI',
        'welcome-text': 'The set of APIs for speech to text conversion and sentiment interpretation. Trained on more than 500,000 hours of audio, our solution covers a wide range of ages, nationalities, accents, and educational levels.',
        'contact': 'Contact',
        'submit': 'Submit',
        'price': 'Price',
        'client': 'Clients',
        'solution': 'Solutions',
        'home' : "Home",
        'faq': 'FAQ',
        'copyright': 'Copyright © 2024 Bruno Lopes. All rights reserved.',
        'clients-section': 'Our Clients',
        'solution-section': 'Solutions',
        'solution-audio-name-async': 'Asynchronous Audio Transcription',
        'solution-audio-async': 'Asynchronous voice transcription API for pre-recorded audio, ideal for extracting insights or transcribing content at scale.',
        'solution-audio-name-real': 'Real-Time Audio Transcription',
        'solution-audio-real': 'Allows the use of real-time subtitles, making lectures and live trainings more accessible.',
        'solution-audio-name-id': 'Audio Language Identification',
        'solution-audio-id': 'Support for transcription in 52 languages, enabling global speech data analysis.',
        'solution-audio-name-analyze': 'Sentiment Analysis',
        'solution-audio-analyze': 'Differentiate between positive and negative speeches for deeper understanding and more assertive business decisions.',
        'contact-section': 'Contact',
        'price-section': 'Pricing',
        'price-beginner': '$29 per month or $328 annually',
        'price-bussiness': '$44 per month or $499 annually',
        'price-enterprise': 'Price on request',
        'price-contact': 'Contact Us',
        'info-beginner-async': 'Asynchronous Audio Transcription - 120 minutes ($0.20 / additional minute)',
        'info-bussiness-async': 'Asynchronous Audio Transcription - 200 minutes ($0.15 / additional minute)',
        'info-beginner-real': 'Real-Time Audio Transcription - 90 minutes ($0.40 / additional minute)',
        'info-bussiness-real': 'Real-Time Audio Transcription - 120 minutes ($0.40 / additional minute)',
        'info-beginner-audio': 'Audio Language Identification - 200 minutes ($0.05 / additional minute)',
        'info-bussiness-audio': 'Audio Language Identification - 500 minutes ($0.03 / additional minute)',
        'info-beginner-analyze': 'Sentiment Analysis from Audio (pre-recorded) - 120 minutes ($0.40 / additional minute)',
        'info-bussiness-analyze': 'Sentiment Analysis from Audio (pre-recorded) - 200 minutes ($0.35 / additional minute)',
        'info-enterprise-async': 'Special prices for large volumes.',
        'info-enterprise-priority': 'Priority technical support.',
        'info-enterprise-dedicate': 'Dedicated account manager.',
        'country': 'Country',
        'terms': 'I agree to the Privacy Policy.',
        'submit': 'Submit',
        'captcha': 'What is 3 + 4?',
        'cookies': 'This site uses cookies to ensure you get the best experience on our website.',
        'more-info': 'Learn More',
        'faq-section': 'Frequently Asked Questions',
        'faq-1-quest': 'How does CheckSpeech AI ensure accuracy in audio transcription?',
        'faq-1-response': 'CheckSpeech AI ensures accuracy in audio transcription by utilizing advanced speech recognition technology combined with deep learning and artificial intelligence. Our solution is trained on over 500,000 hours of audio covering a wide variety of languages, accents, and contexts. Additionally, we conduct constant updates and revisions to improve accuracy and adapt our models to the specific needs of users.',
        'faq-2-quest': 'Do CheckSpeech AI services support different languages and accents?',
        'faq-2-response': 'Yes, CheckSpeech AI services support a wide range of languages and accents. Currently, we offer support for transcription in 52 different languages, ensuring that users around the world can benefit from our solutions. We continue to expand our language library to meet global demands and provide more inclusive services.',
        'faq-3-quest': 'What security measures does CheckSpeech AI implement to protect user data?',
        'faq-3-response': 'CheckSpeech AI takes data security and privacy very seriously. We implement various security measures, including data encryption in transit and at rest, strict access controls, and continuous security monitoring. Furthermore, we comply with international security standards and data protection regulations, such as GDPR, to ensure that user information is handled with the utmost care and confidentiality.',
    },
    'pt': {
        'welcome': 'Bem-vindo ao CheckSpeech AI',
        'welcome-text': 'O conjunto de APIs de conversão de fala em textos e interpretação de sentimentos. Treinada em mais de 500.000 horas de áudios, nossa solução abrange uma ampla variedade de idades, nacionalidades, sotaques e níveis de instrução.',
        'contact': 'Contato',
        'submit': 'Enviar',
        'price': 'Preço',
        'client': 'Clientes',
        'solution': 'Soluções',
        'home' : "Inicio",
        'faq': 'Perguntas Frequentes',
        'copyright' : 'Direitos autorais © 2024 Bruno Lopes. Todos os direitos reservados.',
        'clients-section': 'Nossos Clientes',
        'solution-section': 'Soluções',
        'solution-audio-name-async': 'Transcrição de Áudio Assíncrono',
        'solution-audio-async': 'API de transcrição de voz assíncrona para áudio pré-gravado, ideal para extrair insights ou transcrever conteúdo em escala.',
        "solution-audio-name-real": "Transcrição de Áudio em Tempo Real",
        "solution-audio-real": "Permite o uso de legendas em tempo real, tornando palestras e treinamentos mais acessíveis.",
        "solution-audio-name-id": "Identificação de Idiomas em Áudios",
        "solution-audio-id": "Suporte para transcrição em 52 idiomas, permitindo análise global de dados de fala.",
        "solution-audio-name-analyze": "Análise de Sentimento",
        "solution-audio-analyze": "Diferencie entre falas positivas e negativas para uma compreensão mais profunda e decisões de negócios mais assertivas.",
        "contact-section": "Contato",
        'price-section': 'Preços',
        "price-beginner": "R$29 por mês ou R$328 anual",
        "price-bussiness": "R$44 por mês ou R$499 anual",
        "price-enterprise": "Preço sob consulta",
        "price-contact": "Contate-nos",
        "info-beginner-async": "Transcrição de Áudio Assíncrono - 120 minutos (R$0,20 / minuto excedente)",
        "info-bussiness-async": "Transcrição de Áudio Assíncrono - 200 minutos (R$0,15 / minuto excedente)",
        "info-beginner-real": "Transcrição de Áudio em tempo real - 90 minutos (R$0,40 / minuto excedente)",
        "info-bussiness-real": "Transcrição de Áudio em tempo real - 120 minutos (R$0,40 / minuto excedente)",
        "info-beginner-audio": "Identificação de Idiomas em áudios - 200 minutos (R$0,05 / minuto excedente)",
        "info-bussiness-audio": "Identificação de Idiomas em áudios - 500 minutos (R$0,03 / minuto excedente)",
        "info-beginner-analyze": "Análise de sentimento a partir do áudio (áudio pré-gravado) - 120 minutos (R$0,40 / minuto excedente)",
        "info-bussiness-analyze": "Análise de sentimento a partir do áudio (áudio pré-gravado) - 200 minutos (R$0,35 / minuto excedente)",
        "info-enterprise-async": "Preços especiais para grandes volumes.",
        "info-enterprise-priority": "Prioridade no suporte técnico.",
        "info-enterprise-dedicate": "Gestor de conta dedicado.",
        "country": "País",
        "terms": "Eu concordo com a Política de Privacidade.",
        "submit": "Enviar",
        "captcha": "Quanto é 3 + 4?",
        "cookies": "Este site utiliza cookies para garantir que você obtenha a melhor experiência em nosso site.",
        "more-info": "Saiba Mais",
        "faq-section": "Perguntas Frequentes",
        "faq-1-quest": "Como a CheckSpeech AI garante a precisão na transcrição de áudio?",
        "faq-1-response": "A CheckSpeech AI garante a precisão na transcrição de áudio utilizando tecnologia avançada de reconhecimento de fala, combinada com aprendizado profundo e inteligência artificial. Nossa solução é treinada em mais de 500.000 horas de áudio abrangendo uma ampla variedade de idiomas, sotaques e contextos. Além disso, realizamos constantes atualizações e revisões para melhorar a precisão e adaptar nossos modelos às necessidades específicas dos usuários.",
        "faq-2-quest": "Os serviços da CheckSpeech AI suportam diferentes idiomas e sotaques?",
        "faq-2-response": "Sim, os serviços da CheckSpeech AI suportam uma ampla gama de idiomas e sotaques. Atualmente, oferecemos suporte para transcrição em 52 idiomas diferentes, garantindo que usuários de todo o mundo possam se beneficiar de nossas soluções. Continuamos a expandir nossa biblioteca de idiomas para atender às demandas globais e fornecer serviços mais inclusivos.",
        "faq-3-quest": "Quais medidas de segurança são implementadas pela CheckSpeech AI para proteger os dados dos usuários?",
        "faq-3-response": "A CheckSpeech AI leva a segurança e a privacidade dos dados muito a sério. Implementamos várias medidas de segurança, incluindo criptografia de dados em trânsito e em repouso, controles rigorosos de acesso e monitoramento contínuo de segurança. Além disso, estamos em conformidade com padrões de segurança internacionais e regulamentos de proteção de dados, como GDPR, para garantir que as informações dos usuários sejam manuseadas com o maior cuidado e confidencialidade.",
    },
    'es': {
        'welcome': 'Bienvenido a CheckSpeech AI',
        'welcome-text': 'El conjunto de APIs para la conversión de voz a texto e interpretación de sentimientos. Entrenado en más de 500.000 horas de audio, nuestra solución abarca una amplia gama de edades, nacionalidades, acentos y niveles educativos.',
        'contact': 'Contacto',
        'submit': 'Enviar',
        'price': 'Precio',
        'client': 'Clientes',
        'solution': 'Soluciones',
        'home' : "Comenzar",
        'copyright': 'Derechos de autor © 2024 Bruno Lopes. Todos los derechos reservados.',
        'faq': 'Preguntas Frecuentes',
        'clients-section': 'Nuestros Clientes',
        'solution-section': 'Nuestras Soluciones',
        'solution-audio-name-async': 'Transcripción de Audio Asíncrona',
        'solution-audio-async': 'API de transcripción de voz asíncrona para audio pregrabado, ideal para extraer perspectivas o transcribir contenido a gran escala.',
        'solution-audio-name-real': 'Transcripción de Audio en Tiempo Real',
        'solution-audio-real': 'Permite el uso de subtítulos en tiempo real, haciendo que las conferencias y formaciones en vivo sean más accesibles.',
        'solution-audio-name-id': 'Identificación de Idiomas en Audios',
        'solution-audio-id': 'Soporte para transcripción en 52 idiomas, permitiendo el análisis global de datos de voz.',
        'solution-audio-name-analyze': 'Análisis de Sentimiento',
        'solution-audio-analyze': 'Diferencia entre discursos positivos y negativos para una comprensión más profunda y decisiones de negocio más asertivas.',
        'contact-section': 'Contacto',
        'price-section': 'Precios',
        'price-beginner': '29€ al mes o 328€ anual',
        'price-bussiness': '44€ al mes o 499€ anual',
        'price-enterprise': 'Precio a consultar',
        'price-contact': 'Contáctanos',
        'info-beginner-async': 'Transcripción de Audio Asíncrono - 120 minutos (0,20€ / minuto adicional)',
        'info-bussiness-async': 'Transcripción de Audio Asíncrono - 200 minutos (0,15€ / minuto adicional)',
        'info-beginner-real': 'Transcripción de Audio en Tiempo Real - 90 minutos (0,40€ / minuto adicional)',
        'info-bussiness-real': 'Transcripción de Audio en Tiempo Real - 120 minutos (0,40€ / minuto adicional)',
        'info-beginner-audio': 'Identificación de Idiomas en Audios - 200 minutos (0,05€ / minuto adicional)',
        'info-bussiness-audio': 'Identificación de Idiomas en Audios - 500 minutos (0,03€ / minuto adicional)',
        'info-beginner-analyze': 'Análisis de Sentimiento a partir del Audio (audio pregrabado) - 120 minutos (0,40€ / minuto adicional)',
        'info-bussiness-analyze': 'Análisis de Sentimiento a partir del Audio (audio pregrabado) - 200 minutos (0,35€ / minuto adicional)',
        'info-enterprise-async': 'Precios especiales para grandes volúmenes.',
        'info-enterprise-priority': 'Prioridad en el soporte técnico.',
        'info-enterprise-dedicate': 'Gestor de cuenta dedicado.',
        'country': 'País',
        'terms': 'Acepto la Política de Privacidad.',
        'submit': 'Enviar',
        'captcha': '¿Cuánto es 3 + 4?',
        'cookies': 'Este sitio utiliza cookies para asegurar que obtengas la mejor experiencia en nuestro sitio web.',
        'more-info': 'Más Información',
        'faq-section': 'Preguntas Frecuentes',
        'faq-1-quest': '¿Cómo garantiza CheckSpeech AI la precisión en la transcripción de audio?',
        'faq-1-response': 'CheckSpeech AI garantiza la precisión en la transcripción de audio utilizando tecnología avanzada de reconocimiento de voz combinada con aprendizaje profundo e inteligencia artificial. Nuestra solución está entrenada en más de 500,000 horas de audio que cubren una amplia variedad de idiomas, acentos y contextos. Además, realizamos actualizaciones y revisiones constantes para mejorar la precisión y adaptar nuestros modelos a las necesidades específicas de los usuarios.',
        'faq-2-quest': '¿Los servicios de CheckSpeech AI admiten diferentes idiomas y acentos?',
        'faq-2-response': 'Sí, los servicios de CheckSpeech AI admiten una amplia gama de idiomas y acentos. Actualmente, ofrecemos soporte para transcripción en 52 idiomas diferentes, asegurando que usuarios de todo el mundo puedan beneficiarse de nuestras soluciones. Continuamos expandiendo nuestra biblioteca de idiomas para satisfacer las demandas globales y proporcionar servicios más inclusivos.',
        'faq-3-quest': '¿Qué medidas de seguridad implementa CheckSpeech AI para proteger los datos de los usuarios?',
        'faq-3-response': 'CheckSpeech AI toma muy en serio la seguridad y la privacidad de los datos. Implementamos varias medidas de seguridad, incluida la encriptación de datos en tránsito y en reposo, controles de acceso estrictos y monitoreo de seguridad continuo. Además, cumplimos con estándares internacionales de seguridad y regulaciones de protección de datos, como el GDPR, para asegurar que la información de los usuarios se maneje con el mayor cuidado y confidencialidad.',
    },
    'fr': {
        'welcome': 'Bienvenue chez CheckSpeech AI',
        'welcome-text': "L'ensemble des API pour la conversion de la parole en texte et l'interprétation des sentiments. Formé sur plus de 500 000 heures d'audio, notre solution couvre un large éventail d'âges, de nationalités, d'accents et de niveaux éducatifs.",
        'contact': 'Contact',
        'submit': 'Envoyer',
        'price': 'Prix',
        'client': 'Clients',
        'solution': 'Solutions',
        'home' : "Commencer",
        'faq': 'FAQ',
        'copyright': 'Droits d’auteur © 2024 Bruno Lopes. Tous droits réservés.',
        'clients-section': 'Nos Clients',
        'solution-section': 'Nos Solutions',
        'solution-audio-name-async': 'Transcription Audio Asynchrone',
        'solution-audio-async': "API de transcription vocale asynchrone pour l'audio préenregistré, idéale pour extraire des insights ou transcrire du contenu à grande échelle.",
        'solution-audio-name-real': 'Transcription Audio en Temps Réel',
        'solution-audio-real': "Permet l'utilisation de sous-titres en temps réel, rendant les conférences et les formations en direct plus accessibles.",
        'solution-audio-name-id': "Identification de Langues dans l'Audio",
        'solution-audio-id': 'Support pour la transcription dans 52 langues, permettant une analyse globale des données vocales.',
        'solution-audio-name-analyze': 'Analyse de Sentiment',
        'solution-audio-analyze': "Différenciez les discours positifs et négatifs pour une compréhension plus profonde et des décisions d'affaires plus assertives.",
        'contact-section': 'Contact',
        'price-section': 'Tarification',
        'price-beginner': '29€ par mois ou 328€ annuellement',
        'price-bussiness': '44€ par mois ou 499€ annuellement',
        'price-enterprise': 'Prix sur demande',
        'price-contact': 'Contactez-nous',
        'info-beginner-async': "Transcription Audio Asynchrone - 120 minutes (0,20€ / minute supplémentaire)",
        'info-bussiness-async': "Transcription Audio Asynchrone - 200 minutes (0,15€ / minute supplémentaire)",
        'info-beginner-real': "Transcription Audio en Temps Réel - 90 minutes (0,40€ / minute supplémentaire)",
        'info-bussiness-real': "Transcription Audio en Temps Réel - 120 minutes (0,40€ / minute supplémentaire)",
        'info-beginner-audio': "Identification de Langues dans l'Audio - 200 minutes (0,05€ / minute supplémentaire)",
        'info-bussiness-audio': "Identification de Langues dans l'Audio - 500 minutes (0,03€ / minute supplémentaire)",
        'info-beginner-analyze': "Analyse de Sentiment à partir de l'Audio (préenregistré) - 120 minutes (0,40€ / minute supplémentaire)",
        'info-bussiness-analyze': "Analyse de Sentiment à partir de l'Audio (préenregistré) - 200 minutes (0,35€ / minute supplémentaire)",
        'info-enterprise-async': 'Tarifs spéciaux pour les gros volumes.',
        'info-enterprise-priority': 'Priorité dans le support technique.',
        'info-enterprise-dedicate': 'Gestionnaire de compte dédié.',
        'country': 'Pays',
        'terms': "J'accepte la Politique de Confidentialité.",
        'submit': 'Envoyer',
        'captcha': 'Combien font 3 + 4 ?',
        'cookies': "Ce site utilise des cookies pour vous assurer d'obtenir la meilleure expérience sur notre site Web.",
        'more-info': 'En savoir plus',
        'faq-section': 'Questions Fréquentes',
        "faq-1-quest": "Comment CheckSpeech AI garantit-elle la précision de la transcription audio ?",
        "faq-1-response": "CheckSpeech AI garantit la précision de la transcription audio en utilisant une technologie avancée de reconnaissance vocale, combinée à un apprentissage profond et à l'intelligence artificielle. Notre solution est formée sur plus de 500 000 heures d'audio couvrant une large gamme de langues, d'accents et de contextes. De plus, nous effectuons des mises à jour et des révisions constantes pour améliorer la précision et adapter nos modèles aux besoins spécifiques des utilisateurs.",
        "faq-2-quest": "Les services de CheckSpeech AI prennent-ils en charge différentes langues et accents ?",
        "faq-2-response": "Oui, les services de CheckSpeech AI prennent en charge un large éventail de langues et d'accents. Nous offrons actuellement un support pour la transcription dans 52 langues différentes, garantissant que les utilisateurs du monde entier peuvent bénéficier de nos solutions. Nous continuons à étendre notre bibliothèque de langues pour répondre aux demandes mondiales et fournir des services plus inclusifs.",
        "faq-3-quest": "Quelles mesures de sécurité CheckSpeech AI met-elle en place pour protéger les données des utilisateurs ?",
        "faq-3-response": "CheckSpeech AI prend très au sérieux la sécurité et la confidentialité des données. Nous mettons en œuvre plusieurs mesures de sécurité, y compris le chiffrement des données en transit et au repos, des contrôles d'accès stricts et une surveillance continue de la sécurité. De plus, nous sommes conformes aux normes de sécurité internationales et aux réglementations sur la protection des données, telles que le RGPD, pour garantir que les informations des utilisateurs sont traitées avec le plus grand soin et confidentialité."
    },
};

function changeLanguage(lang) {
    console.log("Changing language to:", lang);
    document.querySelectorAll("[data-translate]").forEach(el => {
        let key = el.getAttribute("data-translate");
        if (translations[lang] && translations[lang][key]) {
            el.innerText = translations[lang][key];
        } else {
            console.log("Missing translation for:", key);
        }
    });
}

document.addEventListener('DOMContentLoaded', function () {
    document.getElementById('languageSelect').addEventListener('change', function () {
        changeLanguage(this.value);
    });

    setInitialLanguage();
});

function setInitialLanguage() {
    const savedLang = localStorage.getItem('selectedLanguage') || 'pt';
    document.getElementById('languageSelect').value = savedLang;
    changeLanguage(savedLang);
}

document.addEventListener('DOMContentLoaded', setInitialLanguage);
